import 'package:flutter/material.dart';
import 'package:aturin_app/features/jadwal/model/aktivitas_model.dart';
import 'package:aturin_app/features/jadwal/services/schedule_api_service.dart';
import 'package:aturin_app/core/services/api/alarm/alarm_api_service.dart';
import 'package:aturin_app/core/services/api/activities/activity_api_service.dart';
import 'package:aturin_app/features/alarm/model/alarm.dart';
import 'package:alarm/alarm.dart';

/// AktivitasService that provides high-level operations for managing activities with alarms
/// Uses ScheduleApiService internally for API operations
class AktivitasService extends ChangeNotifier {
  final ScheduleApiService _scheduleApiService = ScheduleApiService();
  final AlarmApiService _alarmApiService = AlarmApiService();
  final ActivityApiService _activityApiService = ActivityApiService();

  // Expose alarm API service for direct access when needed
  AlarmApiService get alarmApiService => _alarmApiService;

  // ============================
  // AKTIVITAS CRUD OPERATIONS
  // ============================

  /// Get all aktivitas
  Future<List<AktivitasModel>> getAllAktivitas() async {
    try {
      return await _scheduleApiService.getAllAktivitas();
    } catch (e) {
      debugPrint('AktivitasService: Error getting all aktivitas: $e');
      rethrow;
    }
  }

  /// Get aktivitas by date
  Future<List<AktivitasModel>> getAktivitasByDate(DateTime date) async {
    try {
      return await _scheduleApiService.getAktivitasByDate(date);
    } catch (e) {
      debugPrint('AktivitasService: Error getting aktivitas by date: $e');
      rethrow;
    }
  }

  /// Add new aktivitas with optional alarm
  Future<String?> addAktivitas(AktivitasModel aktivitas, DateTime? alarmDateTime) async {
    try {
      AktivitasModel? createdAktivitas;
        // Create alarm first if alarm datetime is provided
      if (alarmDateTime != null) {
        final alarmModel = AlarmModel(
          slug: '', // Will be generated by the server
          alarmDateTime: alarmDateTime,
          alarmEnabled: true,
        );
        
        final createdAlarm = await _alarmApiService.createAlarm(alarmModel);
        if (createdAlarm != null) {
          // Set alarm ID to the aktivitas
          final aktivitasWithAlarm = AktivitasModel(
            id: aktivitas.id,
            userId: aktivitas.userId,
            activityTitle: aktivitas.activityTitle,
            activityDate: aktivitas.activityDate,
            activityStartTime: aktivitas.activityStartTime,
            activityCompleteTime: aktivitas.activityCompleteTime,
            activityCategory: aktivitas.activityCategory,
            alarmId: createdAlarm.id,
            slug: aktivitas.slug,
          );
          
          createdAktivitas = await _scheduleApiService.createAktivitas(aktivitasWithAlarm);
          
          if (createdAktivitas != null) {            // Update alarm with the activity ID
            await _alarmApiService.updateAlarm(
              createdAlarm.slug,
              AlarmModel(
                slug: createdAlarm.slug,
                alarmDateTime: createdAlarm.alarmDateTime,
                alarmEnabled: createdAlarm.alarmEnabled,
              ),
            );
            
            // Schedule system alarm
            await _scheduleSystemAlarm(createdAlarm.id!, alarmDateTime, aktivitas.activityTitle);
          }
        }
      } else {
        // Create aktivitas without alarm
        createdAktivitas = await _scheduleApiService.createAktivitas(aktivitas);
      }
      
      if (createdAktivitas != null) {
        notifyListeners();
        return createdAktivitas.slug;
      }
      
      return null;
    } catch (e) {
      debugPrint('AktivitasService: Error adding aktivitas: $e');
      rethrow;
    }
  }

  /// Update aktivitas by slug with optional alarm update
  Future<AktivitasModel?> updateAktivitasBySlug(
    String slug,
    AktivitasModel updatedAktivitas,
    DateTime? alarmDateTime,
  ) async {
    try {
      // Get current aktivitas to check existing alarm
      final currentAktivitas = await _activityApiService.getActivityBySlug(slug);
      if (currentAktivitas == null) {
        throw Exception('Aktivitas not found with slug: $slug');
      }

      AktivitasModel? result;
      
      // Handle alarm update logic
      if (alarmDateTime != null) {
        if (currentAktivitas.alarmId != null) {
          // Update existing alarm
          final allAlarms = await _alarmApiService.getAllAlarms();
          final existingAlarm = allAlarms.where((a) => a.id == currentAktivitas.alarmId).firstOrNull;
            if (existingAlarm != null) {
            await _alarmApiService.updateAlarm(
              existingAlarm.slug,
              AlarmModel(
                slug: existingAlarm.slug,
                alarmDateTime: alarmDateTime,
                alarmEnabled: true,
              ),
            );
            
            // Update system alarm
            await Alarm.stop(existingAlarm.id!);
            await _scheduleSystemAlarm(existingAlarm.id!, alarmDateTime, updatedAktivitas.activityTitle);
          }
        } else {          // Create new alarm for existing aktivitas
          final alarmModel = AlarmModel(
            slug: '', // Will be generated by the server
            alarmDateTime: alarmDateTime,
            alarmEnabled: true,
          );
          
          final createdAlarm = await _alarmApiService.createAlarm(alarmModel);
          if (createdAlarm != null) {
            // Update aktivitas with new alarm ID
            final aktivitasWithAlarm = AktivitasModel(
              id: updatedAktivitas.id,
              userId: updatedAktivitas.userId,
              activityTitle: updatedAktivitas.activityTitle,
              activityDate: updatedAktivitas.activityDate,
              activityStartTime: updatedAktivitas.activityStartTime,
              activityCompleteTime: updatedAktivitas.activityCompleteTime,
              activityCategory: updatedAktivitas.activityCategory,
              alarmId: createdAlarm.id,
              slug: updatedAktivitas.slug,
            );
            
            result = await _scheduleApiService.updateAktivitas(
              slug: slug,
              data: aktivitasWithAlarm,
            );
            
            // Schedule system alarm
            await _scheduleSystemAlarm(createdAlarm.id!, alarmDateTime, updatedAktivitas.activityTitle);
          }
        }
      } else {
        // No alarm datetime provided
        if (currentAktivitas.alarmId != null) {
          // Remove existing alarm
          final allAlarms = await _alarmApiService.getAllAlarms();
          final existingAlarm = allAlarms.where((a) => a.id == currentAktivitas.alarmId).firstOrNull;
          
          if (existingAlarm != null) {
            await Alarm.stop(existingAlarm.id!);
            await _alarmApiService.deleteAlarm(existingAlarm.slug);
          }
          
          // Update aktivitas without alarm
          final aktivitasWithoutAlarm = AktivitasModel(
            id: updatedAktivitas.id,
            userId: updatedAktivitas.userId,
            activityTitle: updatedAktivitas.activityTitle,
            activityDate: updatedAktivitas.activityDate,
            activityStartTime: updatedAktivitas.activityStartTime,
            activityCompleteTime: updatedAktivitas.activityCompleteTime,
            activityCategory: updatedAktivitas.activityCategory,
            alarmId: null,
            slug: updatedAktivitas.slug,
          );
          
          result = await _scheduleApiService.updateAktivitas(
            slug: slug,
            data: aktivitasWithoutAlarm,
          );
        }
      }
      
      // Update aktivitas if no alarm changes were made
      if (result == null) {
        result = await _scheduleApiService.updateAktivitas(
          slug: slug,
          data: updatedAktivitas,
        );
      }
      
      if (result != null) {
        notifyListeners();
      }
      
      return result;
    } catch (e) {
      debugPrint('AktivitasService: Error updating aktivitas by slug: $e');
      rethrow;
    }
  }

  /// Delete aktivitas by ID
  Future<bool> deleteAktivitas(int id) async {
    try {
      // Get aktivitas by ID first
      final allAktivitas = await _scheduleApiService.getAllAktivitas();
      final aktivitas = allAktivitas.where((a) => a.id == id).firstOrNull;
      
      if (aktivitas?.slug != null) {
        final success = await _scheduleApiService.deleteAktivitas(aktivitas!.slug!);
        if (success) {
          notifyListeners();
        }
        return success;
      }
      
      return false;
    } catch (e) {
      debugPrint('AktivitasService: Error deleting aktivitas: $e');
      rethrow;
    }
  }

  // ============================
  // ALARM HELPER METHODS
  // ============================
  /// Schedule system alarm
  Future<void> _scheduleSystemAlarm(int alarmId, DateTime alarmDateTime, String title) async {
    try {
      final alarmSettings = AlarmSettings(
        id: alarmId,
        dateTime: alarmDateTime,
        assetAudioPath: 'assets/audio/alarm.mp3',
        loopAudio: true,
        vibrate: true,
        warningNotificationOnKill: true,
        androidFullScreenIntent: true,
        volumeSettings: VolumeSettings.staircaseFade(
          volume: null,
          fadeSteps: [VolumeFadeStep(Duration.zero, 0.5)],
          volumeEnforced: false,
        ),
        notificationSettings: NotificationSettings(
          title: 'Reminder Aktivitas',
          body: title,
          stopButton: 'Stop',
          icon: 'notification_icon',
        ),
      );
      
      await Alarm.set(alarmSettings: alarmSettings);
    } catch (e) {
      debugPrint('AktivitasService: Error scheduling system alarm: $e');
      // Don't rethrow as this is not critical for the main operation
    }
  }

  // ============================
  // COMBINED OPERATIONS
  // ============================

  /// Get combined schedule for date
  Future<Map<String, dynamic>> getScheduleByDate(DateTime date) async {
    try {
      return await _scheduleApiService.getScheduleByDate(date);
    } catch (e) {
      debugPrint('AktivitasService: Error getting schedule by date: $e');
      rethrow;
    }
  }

  /// Get combined schedule for date range
  Future<Map<String, dynamic>> getScheduleByDateRange(DateTime startDate, DateTime endDate) async {
    try {
      return await _scheduleApiService.getScheduleByDateRange(startDate, endDate);
    } catch (e) {
      debugPrint('AktivitasService: Error getting schedule by date range: $e');
      rethrow;
    }
  }
}
