import 'package:aturin_app/features/alarm/data/model/alarm.dart';
import 'package:aturin_app/features/task/data/model/task_model.dart';

/// TaskUtilityService - Pure utility service tanpa state
/// Bertanggung jawab hanya untuk business logic dan helper methods
class TaskUtilityService {
  /// Utility methods untuk validasi
  String? validateTitle(String? value) {
    final trimmed = value?.trim() ?? '';
    if (trimmed.isEmpty) return 'Judul wajib diisi';
    if (trimmed.length > 20) return 'Judul maksimal 20 karakter';
    return null;
  }

  String? validateDeadline(DateTime? deadline) {
    if (deadline == null) return 'Batas waktu wajib diisi';
    return null;
  }

  String? validateDuration(Duration? duration) {
    if (duration == null) return 'Estimasi waktu wajib diisi';
    return null;
  }

  String? validateCategory(dynamic category) {
    if (category == null) return 'Kategori wajib diisi';
    return null;
  }

  String? validateAlarm(DateTime? deadline, DateTime? alarm) {
    if (alarm == null) return 'Waktu alarm wajib diisi';
    if (deadline != null && alarm.isAfter(deadline)) {
      return 'Alarm harus sebelum deadline';
    }
    return null;
  }

  /// Utility methods untuk business rules
  bool canEnableAlarm(DateTime? deadline) {
    return deadline != null && 
        deadline.isAfter(DateTime.now().add(const Duration(hours: 1)));
  }

  bool isAlarmTimeValid(DateTime? deadline) {
    if (deadline == null) return false;
    // Alarm diatur 1 jam sebelum deadline, jika (deadline - 1 jam) masih di masa depan
    final alarmTime = deadline.subtract(const Duration(hours: 1));
    return alarmTime.isAfter(DateTime.now());
  }

  /// Check if alarm is valid (alias for isAlarmTimeValid for backward compatibility)
  bool isAlarmValid(DateTime? deadline) {
    return isAlarmTimeValid(deadline);
  }

  /// Task filtering methods
  List<Task> filterTasksByStatus(List<Task> tasks, String filter) {
    switch (filter) {
      case 'Terlambat':
        return tasks
            .where((task) => task.status == TaskStatus.late && !task.isCompleted)
            .toList();
      case 'Belum Selesai':
        return tasks
            .where((task) => !task.isCompleted && task.status != TaskStatus.late)
            .toList()
          ..sort((a, b) => a.deadline.compareTo(b.deadline));
      case 'Selesai':
        return tasks.where((task) => task.isCompleted).toList();
      case 'Semua':
      default:
        final order = [
          TaskStatus.late,
          TaskStatus.today,
          TaskStatus.tomorrow,
          TaskStatus.upcoming,
          TaskStatus.completed,
        ];
        
        return List<Task>.from(tasks)..sort((a, b) {
          if (a.isCompleted != b.isCompleted) {
            return a.isCompleted ? 1 : -1;
          }
          return order.indexOf(a.status).compareTo(order.indexOf(b.status));
        });
    }
  }

  /// Task transformation methods
  Task prepareTaskForUpdate(Task task, {String? slug}) {
    final now = DateTime.now();
    return task.copyWith(
      slug: slug ?? task.slug ?? '',
      updatedAt: now,
    );
  }
  
  Task prepareTaskForCreate(Task task) {
    final now = DateTime.now();
    return task.copyWith(
      userId: task.userId ?? 1,
      slug: '', // Will be generated by backend
      createdAt: now,
      updatedAt: now,
    );
  }

  /// Status checking & update
  Task checkAndUpdateTaskDeadlineStatus(Task task) {
    if (!task.isCompleted && task.deadline.isBefore(DateTime.now())) {
      return task.copyWith(
        taskStatus: TaskDatabaseStatus.terlambat,
      );
    }
    return task;
  }

  /// Alarm time handling
  DateTime getRecommendedAlarmTime(DateTime deadline) {
    // Default: 1 jam sebelum deadline
    return deadline.subtract(const Duration(hours: 1));
  }

  /// Prepare alarm untuk task
  AlarmModel? prepareAlarmForTask(Task task) {
    if (!task.isAlarmEnabled) {
      return null;
    }
    
    final now = DateTime.now();
    final alarmTime = task.alarmDateTime ?? getRecommendedAlarmTime(task.deadline);
    
    return AlarmModel(
      slug: 'task-alarm-${now.millisecondsSinceEpoch}',
      alarmDateTime: alarmTime,
      alarmEnabled: true,
      createdAt: now,
      updatedAt: now,
    );
  }
}
